# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            grant's gazette
tagline:          'a place where stuff goes to die'
description:      'a place where stuff goes to die'
url:              http://www.grantnicholas.github.io/blog/
baseurl:          /blog
comments:         true


author:
  name:           'Grant Nicholas'

paginate:         5

github:
  repo:           https://github.com/grantnicholas
